import { describe, it, expect } from "vitest";
import { buildMarkdownReport, type MarkdownReportContext } from "../src/report/markdown.js";
import { generateHtmlReport, type HtmlReportContext } from "../src/report/html.js";
import { createRuleCatalog } from "../src/catalog.js";
import type { Finding } from "../src/types.js";

const OPTS = { region: "us-east-1", accountId: "111122223333" };

// A pack-shaped catalog: one registry-style entry plus a wildcard detection entry.
const catalog = createRuleCatalog({
  extraEntries: [
    {
      ruleId: "wildcard-action",
      title: "Wildcard action",
      description: "Role grants a wildcard action.",
      threat: "A compromised principal with a wildcard grant can do anything the service allows.",
      rationale: "Least privilege is the control that bounds blast radius after credential theft.",
      severity: "critical",
      appliesTo: "iam_statement",
      complianceFrameworks: ["NIST_AI_RMF"],
    },
    {
      ruleId: "prompt-injection-*",
      title: "Prompt injection signature detected",
      description: "Text matched a known injection signature.",
      threat: "Crafted input is overriding instructions or leaking the system prompt.",
      rationale: "Signature scanning catches the attack at the point of injection.",
      severity: "critical",
      appliesTo: "invocation_log",
      complianceFrameworks: ["OWASP_LLM_TOP10:LLM01"],
    },
  ],
});

const MD_CTX: MarkdownReportContext = {
  defaultTitle: "Test Security Posture Report",
  categorize: (ruleId) =>
    /injection|prompt/.test(ruleId) ? "Prompt Injection" :
    /wildcard|iam/.test(ruleId) ? "IAM & Access" : "Configuration",
  getRuleMetadata: (id) => catalog.get(id),
  footerLines: [
    "*Report generated by [test-pack](https://example.com).*",
    "",
    "**Frameworks referenced:** NIST AI RMF",
  ],
};

const HTML_CTX: HtmlReportContext = {
  defaultTitle: "Test Security Posture Report",
  eyebrow: "Security assessment · test-pack",
  scopeLine: "Assessed against NIST AI RMF.",
  footerLeft: "Generated by test-pack v0.0.0",
  footerRight: "NIST AI RMF & MITRE ATLAS",
  frameworkLabels: { NIST_AI_RMF: "NIST AI RMF 1.0" },
  getRuleMetadata: (id) => catalog.get(id),
};

function finding(overrides: Partial<Finding>): Finding {
  return {
    findingId: "f-1",
    ruleId: "wildcard-action",
    title: "RoleA has a wildcard action",
    severity: "critical",
    status: "FAIL",
    resource: "arn:aws:iam::111122223333:role/RoleA",
    region: "global",
    details: "Role has *:* on *",
    remediation: "Scope the actions.",
    complianceFrameworks: ["NIST_AI_RMF"],
    ...overrides,
  };
}

const FULL_SET: Finding[] = [
  finding({}),
  finding({
    findingId: "f-2", ruleId: "prompt-injection-ignore-previous-instructions", severity: "critical",
    title: "Prompt injection signature detected",
    details: `Request body contains "<script>" & special chars | pipes`,
    complianceFrameworks: ["OWASP_LLM_TOP10:LLM01"],
  }),
  finding({
    findingId: "f-3", ruleId: "uncataloged-high", severity: "high",
    title: "A high finding with no catalog metadata",
    reference: "https://example.com/ref",
  }),
  finding({
    findingId: "f-4", ruleId: "some-medium", severity: "medium",
    title: "A medium finding",
    details: "details | with pipes",
  }),
  finding({ findingId: "f-5", ruleId: "some-low", severity: "low", title: "A low finding" }),
  finding({
    findingId: "f-6", ruleId: "all-clear", severity: "low", status: "PASS",
    title: "No signals detected",
  }),
  finding({
    findingId: "f-7", ruleId: "parse-error", severity: "medium", status: "ERROR",
    title: "Could not parse a document",
  }),
];

describe("buildMarkdownReport", () => {
  it("renders without throwing on empty findings", () => {
    const md = buildMarkdownReport([], OPTS, MD_CTX);
    expect(md).toContain("No security violations detected");
    expect(md).toContain("100/100");
    expect(md.startsWith("# Test Security Posture Report")).toBe(true);
  });

  it("renders all major sections on a full set", () => {
    const md = buildMarkdownReport(FULL_SET, OPTS, MD_CTX);
    expect(md).toContain("## Executive Summary");
    expect(md).toContain("**Overall Risk Rating:** CRITICAL");
    expect(md).toContain("## Severity Breakdown");
    expect(md).toContain("## Critical Findings");
    expect(md).toContain("## High Findings");
    expect(md).toContain("## Other Findings");
    expect(md).toContain("## Remediation Roadmap");
    expect(md).toContain("## Compliance Mapping");
    expect(md).toContain("## Posture Score");
    expect(md).toContain("111122223333");
  });

  it("uses the pack categorize function for the executive summary", () => {
    const md = buildMarkdownReport(FULL_SET, OPTS, MD_CTX);
    expect(md).toContain("**IAM & Access:**");
    expect(md).toContain("**Prompt Injection:**");
    expect(md).toContain("**Configuration:**");
  });

  it("renders threat/rationale for cataloged rules, including wildcard variants", () => {
    const md = buildMarkdownReport(FULL_SET, OPTS, MD_CTX);
    expect(md).toContain("**Threat:** A compromised principal with a wildcard grant");
    expect(md).toContain("**Threat:** Crafted input is overriding instructions");
    expect(md).toContain("**Why it matters:**");
  });

  it("renders the pack footer lines after the separator", () => {
    const md = buildMarkdownReport([], OPTS, MD_CTX);
    expect(md).toContain("*Report generated by [test-pack](https://example.com).*");
    expect(md.trimEnd().endsWith("**Frameworks referenced:** NIST AI RMF")).toBe(true);
  });

  it("respects a custom title", () => {
    const md = buildMarkdownReport([], { ...OPTS, title: "Custom Report Title" }, MD_CTX);
    expect(md.startsWith("# Custom Report Title")).toBe(true);
  });

  it("escapes pipes in table summaries", () => {
    const md = buildMarkdownReport(FULL_SET, OPTS, MD_CTX);
    expect(md).toContain("\\|");
  });
});

describe("generateHtmlReport", () => {
  it("renders without throwing on empty findings", () => {
    const html = generateHtmlReport([], OPTS, HTML_CTX);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("All checks passed");
    expect(html).toContain("Security assessment · test-pack");
    expect(html).toContain("Assessed against NIST AI RMF.");
  });

  it("renders finding cards with globally unique IDs", () => {
    const html = generateHtmlReport(FULL_SET, OPTS, HTML_CTX);
    const ids = [...html.matchAll(/id="(finding-[a-z]+-\d+)"/g)].map(m => m[1]);
    expect(ids.length).toBeGreaterThan(0);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("renders threat and rationale rows for cataloged rules only", () => {
    const html = generateHtmlReport(FULL_SET, OPTS, HTML_CTX);
    expect(html).toContain(">Threat<");
    expect(html).toContain(">Why this matters<");
    expect(html).toContain("A compromised principal with a wildcard grant");
  });

  it("escapes HTML-sensitive characters from finding content", () => {
    const html = generateHtmlReport(FULL_SET, OPTS, HTML_CTX);
    expect(html).toContain("&lt;script&gt;");
    expect(html).not.toContain("<script>\" & special");
    expect(html).toContain("&amp; special chars");
  });

  it("maps framework tags through the pack labels, falling back to the raw tag", () => {
    const html = generateHtmlReport(FULL_SET, OPTS, HTML_CTX);
    expect(html).toContain("NIST AI RMF 1.0");
    expect(html).toContain("OWASP_LLM_TOP10:LLM01"); // unlabeled tag renders as-is
  });

  it("shows the severity bar, roadmap, compliance mapping, and passed section", () => {
    const html = generateHtmlReport(FULL_SET, OPTS, HTML_CTX);
    expect(html).toContain('class="severity-bar"');
    expect(html).toContain("Remediation roadmap");
    expect(html).toContain("Compliance mapping");
    expect(html).toContain("Passed checks (1)");
    expect(html).toContain("Overall risk: Critical");
  });

  it("includes account, region, and the pack footer", () => {
    const html = generateHtmlReport(FULL_SET, OPTS, HTML_CTX);
    expect(html).toContain("111122223333");
    expect(html).toContain("us-east-1");
    expect(html).toContain("Generated by test-pack v0.0.0");
    expect(html).toContain("NIST AI RMF &amp; MITRE ATLAS");
  });
});
