import { describe, it, expect } from "vitest";
import { buildMarkdownReport, generateHtmlReport } from "@miaggy/core";
import { MARKDOWN_CONTEXT, HTML_CONTEXT, categorizeFinding } from "../src/report/context.js";
import { ruleRegistry } from "../src/rules/registry.js";
import "../src/rules/config-rules.js";
import type { McpServerEntry, RegistryInfo } from "../src/types.js";

const server: McpServerEntry = {
  name: "risky",
  source: "/tmp/claude_desktop_config.json",
  client: "claude-desktop",
  command: "npx",
  args: ["-y", "risky-mcp"],
  env: { API_KEY: "sk-FAKEFAKEFAKEFAKEFAKE1234" },
  npmPackage: { spec: "risky-mcp", name: "risky-mcp" },
};

const registry: RegistryInfo = {
  name: "risky-mcp", exists: true, latestVersion: "0.1.0", maintainerCount: 1,
  lastPublishDate: "2024-01-01T00:00:00.000Z", hasInstallScript: true, hasProvenance: false,
};

const FINDINGS = ruleRegistry.evaluate([{ scope: "mcp_server", data: { server, registry } }]);

describe("categorizeFinding", () => {
  it("bins rules into the pack's three categories", () => {
    expect(categorizeFinding("unpinned-server-version")).toBe("Supply Chain");
    expect(categorizeFinding("secrets-in-env-block")).toBe("Secrets & Identity");
    expect(categorizeFinding("config-source-unreadable")).toBe("Coverage");
    expect(categorizeFinding("registry-lookup-skipped")).toBe("Coverage");
  });
});

describe("markdown report", () => {
  it("renders the full pack report with threat metadata and categories", () => {
    const md = buildMarkdownReport(FINDINGS, { region: "local", accountId: "workstation-01" }, MARKDOWN_CONTEXT);
    expect(md.startsWith("# MCP Server Supply Chain Audit")).toBe(true);
    expect(md).toContain("**Supply Chain:**");
    expect(md).toContain("**Secrets & Identity:**");
    expect(md).toContain("**Threat:**");
    expect(md).toContain("@miaggy/mcp-audit");
    expect(md).not.toContain("FAKEFAKE");
  });
});

describe("html report", () => {
  it("renders the pack branding and framework labels", () => {
    const html = generateHtmlReport(FINDINGS, { region: "local", accountId: "workstation-01" }, HTML_CONTEXT);
    expect(html).toContain("Security assessment · mcp-audit");
    expect(html).toContain("OWASP Agentic ASI04 · Supply Chain");
    expect(html).toContain("Generated by @miaggy/mcp-audit v0.1.0");
    expect(html).not.toContain("FAKEFAKE");
  });
});
