import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { buildMarkdownReport, generateHtmlReport } from "@miaggy/core";
import { MARKDOWN_CONTEXT, HTML_CONTEXT, categorizeFinding } from "../src/report/context.js";
import { ruleRegistry } from "../src/rules/registry.js";
import "../src/rules/config-rules.js";
import { coverageSkipFindings } from "../src/tools/audit-mcp-config.js";
import type { McpServerEntry, RegistryInfo } from "../src/types.js";

const { version: PKG_VERSION } = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));

const server: McpServerEntry = {
  name: "risky",
  source: "/tmp/claude_desktop_config.json",
  client: "claude-desktop",
  command: "npx",
  args: ["-y", "risky-mcp"],
  env: { API_KEY: "sk-FAKEFAKEFAKEFAKEFAKE1234" },
  launchShape: "npm",
  packageRef: { ecosystem: "npm", spec: "risky-mcp", name: "risky-mcp" },
};

const registry: RegistryInfo = {
  name: "risky-mcp", exists: true, latestVersion: "0.1.0", maintainerCount: 1,
  lastPublishDate: "2024-01-01T00:00:00.000Z", hasInstallScript: true, hasProvenance: false,
};

const FINDINGS = ruleRegistry.evaluate([{ scope: "mcp_server", data: { server, registry } }]);

describe("categorizeFinding", () => {
  it("bins rules into the pack's three categories", () => {
    expect(categorizeFinding("unpinned-server-version")).toBe("Supply Chain");
    expect(categorizeFinding("secrets-in-env-block")).toBe("Secrets & Identity");
    expect(categorizeFinding("config-source-unreadable")).toBe("Coverage");
    expect(categorizeFinding("registry-lookup-skipped")).toBe("Coverage");
  });
});

describe("markdown report", () => {
  it("renders the full pack report with threat metadata and categories", () => {
    const md = buildMarkdownReport(FINDINGS, { region: "local", accountId: "workstation-01" }, MARKDOWN_CONTEXT);
    expect(md.startsWith("# MCP Server Supply Chain Audit")).toBe(true);
    expect(md).toContain("**Supply Chain:**");
    expect(md).toContain("**Secrets & Identity:**");
    expect(md).toContain("**Threat:**");
    expect(md).toContain("@miaggy/mcp-audit");
    expect(md).not.toContain("FAKEFAKE");
  });
});

describe("coverage-skip (NOT_APPLICABLE) findings render in the human report", () => {
  const skips = coverageSkipFindings([
    { name: "remote-api", source: "/x/.cursor/mcp.json", client: "cursor", args: [], env: {}, launchShape: "remote", url: "http://x/mcp" },
    { name: "docs", source: "/x/.claude.json", client: "claude-code", command: "uvx", args: ["docs@latest"], env: {}, launchShape: "pypi", packageRef: { ecosystem: "pypi", spec: "docs@latest", name: "docs", versionSpec: "latest" } },
  ]);

  it("lists them in a Not Assessed markdown section (not just --json)", () => {
    const md = buildMarkdownReport(skips, { region: "local", accountId: "host" }, MARKDOWN_CONTEXT);
    expect(md).toContain("## Not Assessed");
    expect(md).toContain("remote (url) server");
    expect(md).toContain("PyPI does not publish");
  });

  it("lists them in a Not assessed HTML section", () => {
    const html = generateHtmlReport(skips, { region: "local", accountId: "host" }, HTML_CONTEXT);
    expect(html).toContain("Not assessed (2)");
    expect(html).toContain("cursor:remote-api");
    expect(html).toContain("not assessed"); // health-label count
  });
});

describe("html report", () => {
  it("renders the pack branding and framework labels", () => {
    const html = generateHtmlReport(FINDINGS, { region: "local", accountId: "workstation-01" }, HTML_CONTEXT);
    expect(html).toContain("Security assessment · mcp-audit");
    expect(html).toContain("OWASP Agentic ASI04 · Supply Chain");
    expect(html).toContain(`Generated by @miaggy/mcp-audit v${PKG_VERSION}`);
    expect(html).not.toContain("FAKEFAKE");
  });
});
