// src/report/html.ts
//
// Thin wrapper over the core HTML renderer: injects this pack's branding,
// framework labels, and metadata lookup. Output is byte-identical to
// bedrock-security-mcp v0.1.x EXCEPT the footer version, which now reflects the
// live package version instead of a hardcoded string (the golden suite
// normalizes the version line for this reason).

import { readFileSync } from "node:fs";
import {
  generateHtmlReport as generateCoreHtmlReport,
  type HtmlReportContext,
} from "@miaggy/core";
import type { BedrockSecurityFinding } from "../types.js";
import { getRuleMetadata } from "../rules/catalog.js";

/** The pack's own version, read from package.json so the report footer never
 * drifts from the published version. Resolves in both src (tests) and dist. */
const VERSION: string = (() => {
  try {
    return JSON.parse(readFileSync(new URL("../../package.json", import.meta.url), "utf8")).version;
  } catch {
    return "0.0.0";
  }
})();

/** Human-readable labels for the framework tags the tool cites. */
const FRAMEWORK_LABELS: Record<string, string> = {
  "OWASP_LLM_TOP10:LLM01": "OWASP LLM01 · Prompt Injection",
  "OWASP_LLM_TOP10:LLM02": "OWASP LLM02 · Sensitive Information Disclosure",
  "OWASP_LLM_TOP10:LLM05": "OWASP LLM05 · Improper Output Handling",
  "OWASP_LLM_TOP10:LLM06": "OWASP LLM06 · Excessive Agency",
  "OWASP_LLM_TOP10:LLM07": "OWASP LLM07 · System Prompt Leakage",
  "OWASP_LLM_TOP10:LLM08": "OWASP LLM08 · Vector & Embedding Weaknesses",
  "OWASP_LLM_TOP10:LLM10": "OWASP LLM10 · Unbounded Consumption",
  "OWASP_AGENTIC:ASI01": "OWASP Agentic ASI01 · Goal Hijack",
  "OWASP_AGENTIC:ASI02": "OWASP Agentic ASI02 · Tool Misuse",
  "OWASP_AGENTIC:ASI03": "OWASP Agentic ASI03 · Identity & Privilege Abuse",
  "OWASP_AGENTIC:ASI04": "OWASP Agentic ASI04 · Supply Chain",
  "OWASP_AGENTIC:ASI05": "OWASP Agentic ASI05 · Unexpected Code Execution",
  "OWASP_AGENTIC:ASI07": "OWASP Agentic ASI07 · Insecure Inter-Agent Comms",
  "OWASP_AGENTIC:ASI08": "OWASP Agentic ASI08 · Cascading Failures",
  "NIST_AI_RMF": "NIST AI RMF 1.0",
  "MITRE_ATLAS": "MITRE ATLAS",
  "AWS_WA_ML:SEC-3": "AWS WA ML Lens SEC-3 · Identity & Access",
  "AWS_WA_ML:SEC-6": "AWS WA ML Lens SEC-6 · Data Protection",
  "AWS_WA_ML:SEC-10": "AWS WA ML Lens SEC-10 · Incident Response",
  "AWS_WA_ML:OPS-8": "AWS WA ML Lens OPS-8 · Monitoring",
};

export function frameworkLabel(tag: string): string {
  return FRAMEWORK_LABELS[tag] ?? tag;
}

const HTML_CONTEXT: HtmlReportContext = {
  defaultTitle: "AWS Bedrock Security Posture Report",
  eyebrow: "Security assessment · bedrock-security-mcp",
  scopeLine: "Assessed against OWASP LLM Top 10 (2025), OWASP Agentic Applications Top 10, NIST AI RMF, MITRE ATLAS.",
  footerLeft: `Generated by bedrock-security-mcp v${VERSION}`,
  footerRight: "OWASP LLM Top 10 (2025), OWASP Agentic Applications Top 10, NIST AI RMF, MITRE ATLAS",
  frameworkLabels: FRAMEWORK_LABELS,
  getRuleMetadata,
};

export function generateHtmlReport(
  findings: BedrockSecurityFinding[],
  options: {
    accountId?: string;
    region?: string;
    title?: string;
  } = {}
): string {
  return generateCoreHtmlReport(findings, options, HTML_CONTEXT);
}
