// src/report/markdown.ts
//
// Thin wrapper over the core markdown renderer: injects this pack's title,
// categories, metadata lookup, and footer. Output is byte-identical to
// bedrock-security-mcp v0.1.x (enforced by tests/goldens).

import {
  buildMarkdownReport as buildCoreMarkdownReport,
  type MarkdownReportContext,
} from "@miaggy/core";
import type { BedrockSecurityFinding } from "../types.js";
import { getRuleMetadata } from "../rules/catalog.js";

export { computePostureScore } from "@miaggy/core";

export interface MarkdownReportOptions {
  region: string;
  title?: string;
  accountId?: string;
}

/** Executive-summary category for a finding. Uses the catalog's appliesTo scope
 * (authoritative for all 17 rules); substring fallback covers synthetic
 * ERROR/PASS ruleIds that are not catalog entries (policy-parse-error,
 * iam-enumeration-error, guardrail-read-error, no-injection-signals, invalid-input). */
export function categorizeFinding(ruleId: string): string {
  const meta = getRuleMetadata(ruleId);
  switch (meta?.appliesTo) {
    case "iam_statement":
    case "iam_role":
      return "IAM & Access";
    case "invocation_log":
    case "cloudtrail_event":
    case "cloudtrail_config":
      return "Prompt Injection";
    case "bedrock_config":
    case "bedrock_guardrail":
      return "Bedrock Configuration";
  }
  if (/iam|policy|role|principal/.test(ruleId)) return "IAM & Access";
  if (/injection|prompt|token|hours|invalid-input/.test(ruleId)) return "Prompt Injection";
  return "Bedrock Configuration";
}

const MARKDOWN_CONTEXT: MarkdownReportContext = {
  defaultTitle: "AWS AI/ML Workload Security Posture Report",
  categorize: categorizeFinding,
  getRuleMetadata,
  footerLines: [
    "*Report generated by [bedrock-security-mcp](https://github.com/AUAggy/bedrock-security-mcp) — an opinionated MCP server for AWS AI/ML workload security.*",
    "",
    "**Frameworks referenced:** OWASP LLM Top 10 (2025), OWASP Agentic Applications Top 10, NIST AI RMF, MITRE ATLAS",
  ],
};

export function buildMarkdownReport(
  findings: BedrockSecurityFinding[],
  opts: MarkdownReportOptions
): string {
  return buildCoreMarkdownReport(findings, opts, MARKDOWN_CONTEXT);
}
