// src/report/context.ts
//
// This pack's branding and category data, injected into the core renderers.

import { readFileSync } from "node:fs";
import type { HtmlReportContext, MarkdownReportContext } from "@miaggy/core";
import { getRuleMetadata } from "../rules/catalog.js";

/** The pack's own version, read from package.json so the report footer never
 * drifts from the published version. Resolves in both src (tests) and dist
 * (runtime) — both are two levels below the package root. */
const VERSION: string = (() => {
  try {
    return JSON.parse(readFileSync(new URL("../../package.json", import.meta.url), "utf8")).version;
  } catch {
    return "0.0.0";
  }
})();

export function categorizeFinding(ruleId: string): string {
  if (ruleId === "secrets-in-env-block") return "Secrets & Identity";
  if (/^(tool-|destructive-|oversized-)/.test(ruleId)) return "Tool Manifests";
  if (/-since-baseline$/.test(ruleId) || ruleId === "baseline-unreadable") return "Drift";
  if (ruleId === "config-source-unreadable" || ruleId === "registry-lookup-skipped" || ruleId === "manifest-scan-failed" || ruleId === "coverage-skip") return "Coverage";
  return "Supply Chain";
}

const FRAMEWORK_LABELS: Record<string, string> = {
  "OWASP_LLM_TOP10:LLM02": "OWASP LLM02 · Sensitive Information Disclosure",
  "OWASP_AGENTIC:ASI03": "OWASP Agentic ASI03 · Identity & Privilege Abuse",
  "OWASP_AGENTIC:ASI04": "OWASP Agentic ASI04 · Supply Chain",
  "OWASP_AGENTIC:ASI05": "OWASP Agentic ASI05 · Unexpected Code Execution",
  "NIST_AI_RMF": "NIST AI RMF 1.0",
  "MITRE_ATLAS": "MITRE ATLAS",
};

const TITLE = "MCP Server Supply Chain Audit";
const FRAMEWORKS_LINE = "OWASP Top 10 for Agentic Applications, OWASP LLM Top 10 (2025), NIST AI RMF, MITRE ATLAS";

const META_LABELS = { account: "Machine", region: "Scope" };

export const MARKDOWN_CONTEXT: MarkdownReportContext = {
  defaultTitle: TITLE,
  categorize: categorizeFinding,
  getRuleMetadata,
  metaLabels: META_LABELS,
  footerLines: [
    "*Report generated by [@miaggy/mcp-audit](https://github.com/AUAggy/agent-sec-scanners) — a supply-chain auditor for configured MCP servers.*",
    "",
    `**Frameworks referenced:** ${FRAMEWORKS_LINE}`,
  ],
};

export const HTML_CONTEXT: HtmlReportContext = {
  defaultTitle: TITLE,
  eyebrow: "Security assessment · mcp-audit",
  scopeLine: `Assessed against ${FRAMEWORKS_LINE}.`,
  footerLeft: `Generated by @miaggy/mcp-audit v${VERSION}`,
  footerRight: FRAMEWORKS_LINE,
  frameworkLabels: FRAMEWORK_LABELS,
  getRuleMetadata,
  metaLabels: META_LABELS,
};
